src/SocialNetwork.Web/Controllers/ChatsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Core.Entities;
using SocialNetwork.Core.Services;
using SocialNetwork.Web.Utils;
using SocialNetwork.Web.ViewModels;

namespace SocialNetwork.Web.Controllers
{
    [Authorize]
    public class ChatsController : Controller
    {
        private readonly IChatService _chatService;

        public ChatsController(IChatService chatService)
        {
            _chatService = chatService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.GetUserId();
            var chats = await _chatService.GetUserChatsAsync(userId);

            var model = new ChatsViewModel
            {
                Chats = chats
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Chat(long chatId, int page = 0, int pageSize = 100)
        {
            var userId = User.GetUserId();
            var peer = await _chatService.FindPeerAsync(chatId, userId);
            var messages = await _chatService.GetMessagesAsync(chatId, page, pageSize);

            var model = new ChatViewModel
            {
                ChatId = chatId,
                Peer = peer.UserProfile,
                UserId = userId,

                Page = page,
                PageSize = pageSize,
                Messages = messages
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateChat(long userId)
        {
            await _chatService.CreateChatAsync(User.GetUserId(), userId);

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> CreateMessage([FromBody] CreateMessageViewModel model)
        {
            await _chatService.CreateMessageAsync(model.Text, model.ChatId, User.GetUserId());

            return Ok();
        }
    }
}

src/SocialNetwork.Web/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Core.Entities;
using SocialNetwork.Core.Services;
using SocialNetwork.Core.Utils;
using SocialNetwork.Web.Utils;
using SocialNetwork.Web.ViewModels;

namespace SocialNetwork.Web.Controllers
{
    [Authorize]
    public class FriendsController : UserActionControllerBase
    {
        private readonly IFriendshipService _friendshipService;

        public FriendsController(IUserContext userContext, IFriendshipService friendshipService) : base(userContext)
        {
            _friendshipService = friendshipService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.GetUserId();
            var friendships = await _friendshipService.GetFriendsAsync(userId);

            var model = BuildFriendsViewModel(friendships, userId);

            return View(model);
        }

        private static FriendsViewModel BuildFriendsViewModel(ICollection<Friendship> friendships, long userId)
        {
            return new FriendsViewModel
            {
                Friends = friendships
                    .Where(f => f.Status == FriendshipStatus.RequestAccepted)
                    .Select(f => f.AddresseeId == userId ? f.Requester : f.Addressee)
                    .ToList(),

                IncomingRequests = friendships
                    .Where(f => f.Status == FriendshipStatus.RequestSent && f.AddresseeId == userId)
                    .ToList(),

                PendingRequests = friendships
                    .Where(f => f.Status == FriendshipStatus.RequestSent && f.RequesterId == userId)
                    .ToList()
            };
        }

        [HttpPost]
        [Route("api/friends")]
        public async Task<IActionResult> AddFriend(long userId)
        {
            try
            {
                await _friendshipService.AddAsync(User.GetUserId(), userId);

                return Ok();
            }
            catch (Exception e)
            {
                return StatusCode(500);
            }
        }

        [HttpPut]
        [Route("api/friends")]
        public async Task<IActionResult> AcceptFriend(long userId)
        {
            try
            {
                await _friendshipService.AcceptAsync(userId, User.GetUserId());

                return Ok();
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        [HttpDelete]
        [Route("api/friends/{friendId}")]
        public async Task<IActionResult> DeleteFriend(long friendId)
        {
            try
            {
                await _friendshipService.RemoveAsync(User.GetUserId(), friendId);

                return Ok();
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
    }
}

src/SocialNetwork.Web/Controllers/ProfilesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Core.Entities;
using SocialNetwork.Core.Repositories;
using SocialNetwork.Core.Services;
using SocialNetwork.Core.Utils;
using SocialNetwork.Infrastructure.Services;
using SocialNetwork.Web.Utils;
using SocialNetwork.Web.ViewModels;

namespace SocialNetwork.Web.Controllers
{
    [Authorize]
    public class ProfilesController : UserActionControllerBase
    {
        private readonly IUserProfileRepository _userProfileRepository;
        private readonly IFriendshipService _friendshipService;
        private readonly IMapper _mapper;
        private readonly IUserProfileSearchService _profileSearchService;
        private readonly IChatService _chatService;

        public ProfilesController(
            IMapper mapper,
            IUserContext userContext, 
            IUserProfileRepository userProfileRepository,
            IFriendshipService friendshipService, 
            IUserProfileSearchService profileSearchService, 
            IChatService chatService) : base(userContext)
        {
            _userProfileRepository = userProfileRepository;
            _mapper = mapper;
            _friendshipService = friendshipService;
            _profileSearchService = profileSearchService;
            _chatService = chatService;
        }

        public async Task<IActionResult> Index(int page, int pageSize)
        {
            (page, pageSize) = ValidatePage(page, pageSize);

            var allProfiles = await _userProfileRepository.GetAllUserProfilesAsync(page, pageSize);
            var profiles = FilterOtherUsers(allProfiles);

            return View(new UserProfilesViewModel
            {
                Page = page,
                PageSize = pageSize,
                Profiles = profiles
            });
        }

        public async Task<IActionResult> Search(string query, int page, int pageSize)
        {
            (page, pageSize) = ValidatePage(page, pageSize);

            var allProfiles = await _profileSearchService.SearchUserProfilesAsync(query, page, pageSize);
            var profiles = FilterOtherUsers(allProfiles);

            return View(new UserProfilesSearchViewModel
            {
                Query = query,
                Page = page,
                PageSize = pageSize,
                Profiles = profiles
            });
        }

        public IActionResult My()
        {
            return View(UserContext.CurrentUser.Profile);
        }

        public async Task<IActionResult> Profile(long userId)
        {
            var userProfile = await _userProfileRepository.GetUserProfileAsync(userId);
            var friendship = await _friendshipService.GetFriendshipAsync(User.GetUserId(), userId);
            var chat = await _chatService.FindChatAsync(User.GetUserId(), userId);

            return View(BuildProfileViewModel(userProfile, friendship, chat));
        }

        private ICollection<UserProfile> FilterOtherUsers(ICollection<UserProfile> profiles) =>
            profiles.Where(p => p.UserId != UserContext.CurrentUser.Id).ToList();

        private (int page, int pageSize) ValidatePage(int page, int pageSize)
        {
            const int defaultPageSize = 30;

            if (page <= 0) page = 0;
            if (pageSize <= 0 || pageSize > 100) pageSize = defaultPageSize;

            return (page, pageSize);
        }

        private UserProfileViewModel BuildProfileViewModel(UserProfile userProfile, Friendship friendship, ChatMember chat)
        {
            var model = _mapper.Map<UserProfile, UserProfileViewModel>(userProfile);

            model.IsFriendshipInitiated = friendship != null;

            if (friendship != null)
            {
                model.FriendshipStatus = friendship.Status;
                model.IsUserRequester = userProfile.UserId == friendship.AddresseeId;
                model.FriendshipCreated = friendship.Created;
            }

            if (chat != null)
            {
                model.ChatCreated = true;
                model.ChatId = chat.ChatId;
            }

            return model;
        }
    }
}

src/SocialNetwork.Web/Views/Profiles/Index.cshtml
@model SocialNetwork.Web.ViewModels.UserProfilesViewModel

@{
    Layout = "../_Layout";
    ViewBag.Title = "Profiles";
}


<div class="profiles-container">
    @foreach (var profile in Model.Profiles)
    {
        <div class="card user-card">
            <div class="card-body">
                <h5 class="card-title">@profile.FirstName @profile.LastName</h5>
                <h6 class="card-subtitle mb-2 text-muted">City: @profile.City, Age: @profile.Age</h6>
                <p class="card-text">@profile.Interests</p>
                <a class="card-link" asp-controller="Profiles" asp-action="Profile" asp-route-userId="@profile.UserId">Go to profile</a>
            </div>
        </div>
    }
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link @(Model.Page == 0 ? "disabled" : "")" href="@Url.Action("Index", new {page = Model.Page - 1, pageSize = Model.PageSize})">
                Previous
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="@Url.Action("Index", new {page = Model.Page + 1, pageSize = Model.PageSize})">Next</a>
        </li>
    </ul>
</nav>

src/SocialNetwork.Web/Views/Profiles/My.cshtml
@model SocialNetwork.Core.Entities.UserProfile

@{
    Layout = "../_Layout";
    ViewBag.Title = @Model.FirstName + " Profile";
}


<div>
    <h2>Your profile:</h2>
    <p><b>FirstName:</b> @Model.FirstName</p>
    <p><b>LastName:</b> @Model.LastName</p>
    <p><b>Age:</b> @Model.Age</p>
    <p><b>City:</b> @Model.City</p>
    <p><b>Interests:</b> @Model.Interests</p>
</div>

src/SocialNetwork.Web/Views/Profiles/Profile.cshtml
@using SocialNetwork.Core.Entities
@model SocialNetwork.Web.ViewModels.UserProfileViewModel

@{
    Layout = "../_Layout";
    ViewBag.Title = @Model.FirstName + "Profile";
}


<div>
    <h2>User profile:</h2>
    <p><b>FirstName:</b> @Model.FirstName</p>
    <p><b>LastName:</b> @Model.LastName</p>
    <p><b>Age:</b> @Model.Age</p>
    <p><b>City:</b> @Model.City</p>
    <p><b>Interests:</b> @Model.Interests</p>

    @if (!Model.IsFriendshipInitiated || Model.FriendshipStatus == FriendshipStatus.RemovedByAddressee || Model.FriendshipStatus == FriendshipStatus.RemovedByRequester)
    {
        <button id="add-friend-button" >Add friend</button>
    }
    else
    {
        @if (Model.FriendshipStatus == FriendshipStatus.RequestAccepted)
        {
            <p>We are friends!</p>
        }
        else if (Model.IsUserRequester && Model.FriendshipStatus == FriendshipStatus.RequestSent)
        {
            <p>Friend request sent</p>
        }
    }
    
    @if (Model.ChatCreated)
    {
        <a id="go-to-chat-button">Go to chat</a>
    }
    else
    {
        <button id="create-chat-button">Create chat</button>
    }
</div>

<script>
    document.addEventListener("DOMContentLoaded", function(event) {
        if (document.getElementById("add-friend-button")) {
            document.getElementById("add-friend-button").onclick = function () {
                fetch("@Url.Action("AddFriend", "Friends", new { userId = @Model.UserId })", { method: 'POST' })
                    .then(data => alert("success, refresh page"))
                    .catch(data => alert("error: " + data));
            }
        }

        if (document.getElementById("create-chat-button")) {
            document.getElementById("create-chat-button").onclick = function () {
                fetch("@Url.Action("CreateChat", "Chats", new { userId = @Model.UserId })", { method: 'POST' })
                    .then(data => window.location.assign("@Url.Action("Index", "Chats")"))
                    .catch(data => alert("error: " + data));
            }
        }
    });
</script>

src/SocialNetwork.Web/Views/Profiles/Search.cshtml
@model SocialNetwork.Web.ViewModels.UserProfilesSearchViewModel

@{
    Layout = "../_Layout";
    ViewBag.Title = "Find Profiles";
}

<div class="search-field">
    <form asp-controller="Profiles" asp-action="Search" method="get">
        <input type="text" name="query" />
    </form>
</div>


<div class="profiles-container">
    @foreach (var profile in Model.Profiles)
    {
        <div class="card user-card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@profile.FirstName @profile.LastName</h5>
                <h6 class="card-subtitle mb-2 text-muted">City: @profile.City, Age: @profile.Age</h6>
                <p class="card-text">@profile.Interests</p>
                <a class="card-link" asp-controller="Profiles" asp-action="Profile" asp-route-userId="@profile.UserId">Go to profile</a>
            </div>
        </div>
    }
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link @(Model.Page == 0 ? "disabled" : "")" href="@Url.Action("Search", new { query = Model.Query, page = Model.Page - 1, pageSize = Model.PageSize})">
                Previous
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="@Url.Action("Search", new { query = Model.Query, page = Model.Page + 1, pageSize = Model.PageSize})">Next</a>
        </li>
    </ul>
</nav>