src/SocialNetwork.Web/ViewModels/CreatePostViewModel.cs
namespace SocialNetwork.Web.ViewModels
{
    public class CreatePostViewModel
    {
        public string Text { get; set; }
    }
}

src/SocialNetwork.Web/Controllers/NewsFeedController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Core.Services;
using SocialNetwork.Core.Utils;
using SocialNetwork.Web.Utils;
using SocialNetwork.Web.ViewModels;

namespace SocialNetwork.Web.Controllers
{
    [Route("feed")]
    [Authorize]
    public class NewsFeedController : UserActionControllerBase
    {
        private readonly IUserPostService _userPostService;

        public NewsFeedController(IUserContext userContext, IUserPostService userPostService) : base(userContext)
        {
            _userPostService = userPostService;
        }

        [HttpGet]
        [Route("")]
        public async Task<IActionResult> Feed()
        {
            var news = await _userPostService.GetNewsFeedAsync(HttpContext.User.GetUserId());

            return View("Index", news);
        }

        [HttpGet]
        [Route("new")]
        public IActionResult CreatePost() => View("CreatePost");

        [HttpPost]
        [Route("new")]
        public async Task<IActionResult> CreatePost(CreatePostViewModel model)
        {
            await _userPostService.AddPostAsync(model.Text, HttpContext.User.GetUserId());

            return RedirectToAction("Feed");
        }
    }
}

src/SocialNetwork.Web/Views/NewsFeed/CreatePost.cshtml
@model SocialNetwork.Web.ViewModels.CreatePostViewModel

@{
    Layout = "../_Layout";
    ViewBag.Title = "Create post";
}

<form method="post" asp-action="CreatePost">
    <div>
        <label class="sr-only" asp-for="Text">Type what you want no share with friends</label>
        <textarea class="form-control" asp-for="Text" placeholder="Hi there!"></textarea>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Post!</button>
</form>

src/SocialNetwork.Web/Views/NewsFeed/Index.cshtml
@model ICollection<SocialNetwork.Core.Entities.UserPost>

@{
    Layout = "../_Layout";
    ViewBag.Title = "News";
}

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.7/signalr.min.js"></script>

    <script>
        const connection = new signalR.HubConnectionBuilder()
            .withUrl("/newsFeedHub")
            .configureLogging(signalR.LogLevel.Information)
            .build();

        async function start() {
            try {
                await connection.start();
                console.log("SignalR Connected.");
            } catch (err) {
                console.log(err);
                setTimeout(start, 5000);
            }
        };

        connection.onclose(async () => {
            await start();
        });

        connection.on("addPost",
            post => {
                console.log(`received post ${JSON.stringify(post)}`);

                const postElement = document.createElement("div");
                postElement.classList.add("card");
                postElement.classList.add("feed-post");

                const headerElement = document.createElement("div");
                headerElement.classList.add("card-header");

                const headerTitleElement = document.createElement("h5");
                headerTitleElement.innerText = post.userProfile.firstName + ' ' + post.userProfile.lastName;

                const headerDateElement = document.createElement("span");
                headerDateElement.classList.add("feed-post-date");
                headerDateElement.innerText = post.created.split("T")[0];

                headerElement.appendChild(headerTitleElement);
                headerElement.appendChild(headerDateElement);

                const bodyElement = document.createElement("div");
                bodyElement.classList.add("card-body");

                bodyElement.innerText = post.text;

                postElement.appendChild(headerElement);
                postElement.appendChild(bodyElement);

                const postsElement = document.getElementById("feed-posts-container");

                postsElement.appendChild(postElement);
            });

        // Start the connection.
        start();
    </script>
}

<div>
    Create new post <a asp-controller="NewsFeed" asp-action="CreatePost">here</a>
</div>

<div class="feed-posts-container" id="feed-posts-container">
    @foreach (var post in Model)
    {
        <div class="card feed-post">
            <div class="card-header">
                <h5>@post.UserProfile?.FirstName @post.UserProfile?.LastName</h5>
                <span class="feed-post-date">@post.Created.ToString("yyyy-MM-dd")</span>
            </div>
            <div class="card-body">@post.Text</div>
        </div>
    }
</div>