src/SocialNetwork.Web/ViewModels/FriendsViewModel.cs
using System.Collections.Generic;
using SocialNetwork.Core.Entities;

namespace SocialNetwork.Web.ViewModels
{
    public class FriendsViewModel
    {
        public ICollection<UserProfile> Friends { get; set; }
        public ICollection<Friendship> PendingRequests { get; set; }
        public ICollection<Friendship> IncomingRequests { get; set; }
    }
}

src/SocialNetwork.Web/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Core.Entities;
using SocialNetwork.Core.Services;
using SocialNetwork.Core.Utils;
using SocialNetwork.Web.Utils;
using SocialNetwork.Web.ViewModels;

namespace SocialNetwork.Web.Controllers
{
    [Authorize]
    public class FriendsController : UserActionControllerBase
    {
        private readonly IFriendshipService _friendshipService;

        public FriendsController(IUserContext userContext, IFriendshipService friendshipService) : base(userContext)
        {
            _friendshipService = friendshipService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.GetUserId();
            var friendships = await _friendshipService.GetFriendsAsync(userId);

            var model = BuildFriendsViewModel(friendships, userId);

            return View(model);
        }

        private static FriendsViewModel BuildFriendsViewModel(ICollection<Friendship> friendships, long userId)
        {
            return new FriendsViewModel
            {
                Friends = friendships
                    .Where(f => f.Status == FriendshipStatus.RequestAccepted)
                    .Select(f => f.AddresseeId == userId ? f.Requester : f.Addressee)
                    .ToList(),

                IncomingRequests = friendships
                    .Where(f => f.Status == FriendshipStatus.RequestSent && f.AddresseeId == userId)
                    .ToList(),

                PendingRequests = friendships
                    .Where(f => f.Status == FriendshipStatus.RequestSent && f.RequesterId == userId)
                    .ToList()
            };
        }

        [HttpPost]
        [Route("api/friends")]
        public async Task<IActionResult> AddFriend(long userId)
        {
            try
            {
                await _friendshipService.AddAsync(User.GetUserId(), userId);

                return Ok();
            }
            catch (Exception e)
            {
                return StatusCode(500);
            }
        }

        [HttpPut]
        [Route("api/friends")]
        public async Task<IActionResult> AcceptFriend(long userId)
        {
            try
            {
                await _friendshipService.AcceptAsync(userId, User.GetUserId());

                return Ok();
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        [HttpDelete]
        [Route("api/friends/{friendId}")]
        public async Task<IActionResult> DeleteFriend(long friendId)
        {
            try
            {
                await _friendshipService.RemoveAsync(User.GetUserId(), friendId);

                return Ok();
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
    }
}

src/SocialNetwork.Web/Controllers/ProfilesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Core.Entities;
using SocialNetwork.Core.Repositories;
using SocialNetwork.Core.Services;
using SocialNetwork.Core.Utils;
using SocialNetwork.Infrastructure.Services;
using SocialNetwork.Web.Utils;
using SocialNetwork.Web.ViewModels;

namespace SocialNetwork.Web.Controllers
{
    [Authorize]
    public class ProfilesController : UserActionControllerBase
    {
        private readonly IUserProfileRepository _userProfileRepository;
        private readonly IFriendshipService _friendshipService;
        private readonly IMapper _mapper;
        private readonly IUserProfileSearchService _profileSearchService;
        private readonly IChatService _chatService;

        public ProfilesController(
            IMapper mapper,
            IUserContext userContext, 
            IUserProfileRepository userProfileRepository,
            IFriendshipService friendshipService, 
            IUserProfileSearchService profileSearchService, 
            IChatService chatService) : base(userContext)
        {
            _userProfileRepository = userProfileRepository;
            _mapper = mapper;
            _friendshipService = friendshipService;
            _profileSearchService = profileSearchService;
            _chatService = chatService;
        }

        public async Task<IActionResult> Index(int page, int pageSize)
        {
            (page, pageSize) = ValidatePage(page, pageSize);

            var allProfiles = await _userProfileRepository.GetAllUserProfilesAsync(page, pageSize);
            var profiles = FilterOtherUsers(allProfiles);

            return View(new UserProfilesViewModel
            {
                Page = page,
                PageSize = pageSize,
                Profiles = profiles
            });
        }

        public async Task<IActionResult> Search(string query, int page, int pageSize)
        {
            (page, pageSize) = ValidatePage(page, pageSize);

            var allProfiles = await _profileSearchService.SearchUserProfilesAsync(query, page, pageSize);
            var profiles = FilterOtherUsers(allProfiles);

            return View(new UserProfilesSearchViewModel
            {
                Query = query,
                Page = page,
                PageSize = pageSize,
                Profiles = profiles
            });
        }

        public IActionResult My()
        {
            return View(UserContext.CurrentUser.Profile);
        }

        public async Task<IActionResult> Profile(long userId)
        {
            var userProfile = await _userProfileRepository.GetUserProfileAsync(userId);
            var friendship = await _friendshipService.GetFriendshipAsync(User.GetUserId(), userId);
            var chat = await _chatService.FindChatAsync(User.GetUserId(), userId);

            return View(BuildProfileViewModel(userProfile, friendship, chat));
        }

        private ICollection<UserProfile> FilterOtherUsers(ICollection<UserProfile> profiles) =>
            profiles.Where(p => p.UserId != UserContext.CurrentUser.Id).ToList();

        private (int page, int pageSize) ValidatePage(int page, int pageSize)
        {
            const int defaultPageSize = 30;

            if (page <= 0) page = 0;
            if (pageSize <= 0 || pageSize > 100) pageSize = defaultPageSize;

            return (page, pageSize);
        }

        private UserProfileViewModel BuildProfileViewModel(UserProfile userProfile, Friendship friendship, ChatMember chat)
        {
            var model = _mapper.Map<UserProfile, UserProfileViewModel>(userProfile);

            model.IsFriendshipInitiated = friendship != null;

            if (friendship != null)
            {
                model.FriendshipStatus = friendship.Status;
                model.IsUserRequester = userProfile.UserId == friendship.AddresseeId;
                model.FriendshipCreated = friendship.Created;
            }

            if (chat != null)
            {
                model.ChatCreated = true;
                model.ChatId = chat.ChatId;
            }

            return model;
        }
    }
}

src/SocialNetwork.Web/Views/Friends/Index.cshtml
@model SocialNetwork.Web.ViewModels.FriendsViewModel

@{
    Layout = "../_Layout";
    ViewBag.Title = "Friends";
}


<div class="frinds-base-container">
    <div class="friends-block-container">
        <h1>Friends:</h1>
        
        <div class="friends-container">
            @foreach (var profile in Model.Friends)
            {
                <div class="card user-card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@profile.FirstName @profile.LastName</h5>
                        <h6 class="card-subtitle mb-2 text-muted">City: @profile.City, Age: @profile.Age</h6>
                        <p class="card-text">@profile.Interests</p>
                        <a class="card-link" asp-controller="Profiles" asp-action="Profile" asp-route-userId="@profile.UserId">Go to profile</a>
                        <button class="remove-friend-button" data-userId="@profile.UserId">Remove friend</button>
                    </div>
                </div>
            }
        </div>
    </div>
    
    <div class="friends-block-container">
        <h1>Incoming requests:</h1>

        <div class="friends-container">
            @foreach (var friendship in Model.IncomingRequests)
            {
                <div class="card user-card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@friendship.Requester.FirstName @friendship.Requester.LastName</h5>
                        <h6 class="card-subtitle mb-2 text-muted">City: @friendship.Requester.City, Age: @friendship.Requester.Age</h6>
                        <p class="card-text">@friendship.Requester.Interests</p>
                        <a class="card-link" asp-controller="Profiles" asp-action="Profile" asp-route-userId="@friendship.Requester.UserId">Go to profile</a>
                        <button class="accept-friend-button" data-userId="@friendship.RequesterId">Accept</button>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="friends-block-container">
        <h1>Pending requests:</h1>
        
        <div class="friends-container">
            @foreach (var friendship in Model.PendingRequests)
            {
                <div class="card user-card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">@friendship.Addressee.FirstName @friendship.Addressee.LastName</h5>
                        <h6 class="card-subtitle mb-2 text-muted">City: @friendship.Addressee.City, Age: @friendship.Addressee.Age</h6>
                        <p class="card-text">@friendship.Addressee.Interests</p>
                        <a class="card-link" asp-controller="Profiles" asp-action="Profile" asp-route-userId="@friendship.Addressee.UserId">Go to profile</a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        var acceptButtons = document.getElementsByClassName("accept-friend-button");
        for (var i = 0; i < acceptButtons.length; i++) {
            acceptButtons[i].onclick = function (e) {
                var userId = e.target.getAttribute("data-userId");
                fetch("@Url.Action("AcceptFriend", "Friends")?userId=" + userId, { method: 'PUT' })
                    .then(response => response.status === 200 && alert("friend accepted, refresh page"))
                    .catch(data => alert("error: " + data));
            }
        }

        var removeButtons = document.getElementsByClassName("remove-friend-button");
        for (var i = 0; i < removeButtons.length; i++) {
            removeButtons[i].onclick = function (e) {
                var userId = e.target.getAttribute("data-userId");
                console.log(userId);
                fetch("@Url.Action("AcceptFriend", "Friends")/" + userId, { method: 'DELETE' })
                    .then(response => response.status === 200 && alert("friend removed, refresh page"))
                    .catch(data => alert("error: " + data));
            }
        }
    });
</script>